# build pipeline

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build --confiuration $(buildConfiguration)'
- script: echo pipeline completed
  displayName: Completion Message